# Set position setpoints

dt: 0.02 # [seconds]
max_reach_time: 5.0 # [seconds]

xy_threshold: 0.2 #[meters]
z_threshold: 0.2 #[meters]

object_name: "srl_box" #name of object to be grasped
quad_name: "srl_quad" #name of object to be grasped

#prefix of DDS topic
topic_prefix: "topic_"
